changesDir: .changes
unreleasedDir: unreleased
headerPath: .changes/header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'

kinds:
  - label: Breaking Change
    auto: major
  - label: Feature
    auto: minor
  - label: Enhancement
    auto: minor
  - label: Bug Fix
    auto: patch
  - label: Documentation
    auto: patch
  - label: Internal
    auto: patch

newlines:
  afterChangelogHeader: 1
  beforeChangelogVersion: 1
  endOfVersion: 1
